### ISSUE TITLE
Make `availVertex` vector and re-write generate edge

### ISSUE THREAD

**Issue by mishashevelinn** [mishashevelinn/Project#15]
`int avail[n], num_avail=0;`\
   `if (!G.visited[u] && G.Adj[u].size() != 3)`\
     `avail[num_avail++] = u;`\
  `random from avail`\

**Comment by mishashevelinn** [comment]
int avail[n], num_avail=0; if (!G.visited[u] && G.Adj[u].size() != 3) avail[num_avail++] = u; random from avail

**Comment by mishashevelinn** [comment]
`int avail[n], num_avail=0;
   if (!G.visited[u] && G.Adj[u].size() != 3)
     avail[num_avail++] = u;
  random from avail`

**Comment by Talsha1995** [comment]
Done.
